### ISSUE TITLE
의존성 역전 

### ISSUE THREAD

**Issue by Loco-shoplive** [YunSeokVV/RetrofitPractice#2]
https://github.com/YunSeokVV/RetrofitPractice/blob/1793a3ff4e01995354410193badfceb0037aad9a/app/src/main/java/com/example/retrofitpracticewithdustapi/repository/DustRepository.kt#L17

fun makeApiCall(callback : (Citys) -> Unit) {
dust.enqueue(object: Callback<DustModel> {
            override fun onResponse(call: Call<DustModel>, response: Response<DustModel>) {
                val cityResult : Citys? = response.body()?.response?.body?.items?.get(0)
                cityResult?.let { callback(it) }
            }

            override fun onFailure(call: Call<DustModel>, t: Throwable) {
            }
        })
}

->

fun makeApiCall(callback : Callback<DustModel>) {
 dust.enqueue(callback)
}

**Comment by YunSeokVV** [comment]
의존성 역전이 무엇인지 공부를 하게 되는 계기가 되었습니다. 
제가 기존에 짰던 코드에서 잘못됐었던 부분은 makeAPiCall 메소드의 매개변수 부분이였습니다.
하위모듈(DustRepository.kt)에서 인터페이스나 추상클래스같은 상위모듈에 의존해야 합니다. 그래서 아래와 같이 매개변수가 CallBack 인터페이스로 설정되는게 옳은 표현이입니다.
    
    fun makeApiCall2(callback : Callback<Citys>){
      //  ..do something
    }
    
    감사합니다.
