### ISSUE TITLE
API 모듈 개선

### ISSUE THREAD

**Issue by Loco-shoplive** [YunSeokVV/RetrofitPractice#3]
https://github.com/YunSeokVV/RetrofitPractice/blob/1793a3ff4e01995354410193badfceb0037aad9a/app/src/main/java/com/example/retrofitpracticewithdustapi/repository/DustRepository.kt#L23

response.body()?.response -> response 해서 객체만 받을 수 있게

**Comment by YunSeokVV** [comment]
이 부분은 넘어가도 된다고 말씀해주셨습니다.
