### ISSUE TITLE
Handler 로 main thread 변경하기

### ISSUE THREAD

**Issue by Loco-shoplive** [YunSeokVV/RetrofitPractice#4]
https://github.com/YunSeokVV/RetrofitPractice/blob/1793a3ff4e01995354410193badfceb0037aad9a/app/src/main/java/com/example/retrofitpracticewithdustapi/viewModel/MainActivityViewModel.kt#L24

Handler 로 main thread 변경하기

deprecated 가 안된 main looper 로 적용하기

**Comment by YunSeokVV** [comment]
검색하면서 공부해본 결과 몇가지 궁금한점이 생겼습니다. 수업시간에 여쭤보도록 하겠습니다.
