### ISSUE TITLE
MutableLiveData 관련

### ISSUE THREAD

**Issue by Loco-shoplive** [YunSeokVV/RetrofitPractice#5]
https://github.com/YunSeokVV/RetrofitPractice/blob/1793a3ff4e01995354410193badfceb0037aad9a/app/src/main/java/com/example/retrofitpracticewithdustapi/view/MainActivity.kt#L41C9-L41C30

 viewModel.getCityTemp().observe(this, Observer {data ->
            updateUI(data)
        })

viewModel.getCityTemp().value =  ????

view 에서 비지니스로직 접근이 됩니다.

**Comment by YunSeokVV** [comment]
강의 녹화된거 한번 더 돌려보고 어떤 말씀이신지 이해했네요.. 언급해주신대로 VIewModel에서 LiveData의 자료형을 MutableLiveData 로 설정한뒤 get메소드로 뷰에서 접근하게 되면 postValue나 setValue로 값을 설정해지는게 가능해서 오류가 일어날 가능성을 굳이 제가 스스로 만들게 되는 것이네요.
여러번 언급해주신 부분이였는데 제가 조금 더 귀담아 듣도록 노력하겠습니다. 감사합니다.
