### ISSUE TITLE
api 를 보다 다양하게 사용하기

### ISSUE THREAD

**Issue by Loco-shoplive** [YunSeokVV/RetrofitPractice#6]
https://github.com/YunSeokVV/RetrofitPractice/blob/1793a3ff4e01995354410193badfceb0037aad9a/app/src/main/java/com/example/retrofitpracticewithdustapi/DustApiProvider.kt#L15C27-L15C34

DustApi -> T 제네릭으로 
반복되는 코드는 helper 나 module형태로

**Comment by YunSeokVV** [comment]
슬랙에서 방법을 알려주셔서 참고하였습니다.
말씀해주신대로 inline과 reified 에 관해서 공부하고 정리했습니다. 수업전에 공유해드리겠습니다.
감사합니다.
